-- Create ANALYTICS schema if it doesn't exist
CREATE SCHEMA IF NOT EXISTS Cursor_Demo.ANALYTICS;

-- Create a file format for compressed JSON files
CREATE OR REPLACE FILE FORMAT Cursor_Demo.ANALYTICS.JSON_GZ_FORMAT
	TYPE=JSON
    STRIP_OUTER_ARRAY=TRUE
    REPLACE_INVALID_CHARACTERS=TRUE
    DATE_FORMAT=AUTO
    TIME_FORMAT=AUTO
    TIMESTAMP_FORMAT=AUTO;

CREATE OR REPLACE TABLE Cursor_Demo.ANALYTICS.RAW_JSON_DATA_NEW (
    FILE_NAME VARCHAR,
    FILE_LOAD_TIME TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    JSON_DATA VARIANT
);

-- Create a task to load new JSON files every 15 seconds
CREATE OR REPLACE TASK Cursor_Demo.ANALYTICS.LOAD_JSON_FILES_NEW
    WAREHOUSE = CORTEX_DEMO_WH
    SCHEDULE = '15 seconds'
AS
    COPY INTO "CURSOR_DEMO"."ANALYTICS"."RAW_JSON_DATA_NEW" 
    FROM (SELECT 
        METADATA$FILENAME,
        CURRENT_TIMESTAMP(),
        $1::VARIANT
        FROM '@"CURSOR_DEMO"."DATA_PREP"."CALL_DATA_STAGE"') 
    FILE_FORMAT = '"CURSOR_DEMO"."ANALYTICS"."JSON_GZ_FORMAT"' 
    ON_ERROR=ABORT_STATEMENT 
 ;


-- Resume the task to start processing
ALTER TASK Cursor_Demo.ANALYTICS.LOAD_JSON_FILES_NEW RESUME;

-- Suspend the task
ALTER TASK Cursor_Demo.ANALYTICS.LOAD_JSON_FILES_NEW SUSPEND;


-- Example usage:
-- CALL Cursor_Demo.ANALYTICS.LOAD_NEW_JSON_FILES(); 